export {PrincipalPage} from "./principal/principal";
export {AjustesPage} from "./ajustes/ajustes";
export {Ajustes2Page} from "./ajustes2/ajustes2";
export {ModalPage} from "./modal/modal";
export {nfcPage} from "./nfc/nfc";
export {PerfilesPage} from "./perfilesMuertos/perfiles";
export {TabsPage} from "./tabs/tabs";  
export {BuscarPage} from "./buscar/buscar";
export {MapaDirectionPage} from "./mapa-direction/mapa-direction";